/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3.1/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    java
}


repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven {
        url = uri("https://mymavenrepo.com/repo/wNFFvG0nRh9xnwHJXqEQ/")
    }
}

dependencies {
    
    compile("com.ibm.gol:GameOfLifeHdM:1.0.0")
    
    compile("com.google.code.gson:gson:2.8.5")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

tasks.withType<Jar> {
    baseName = "gol-cloud-function"
    version =  "0.0.1"
    from(configurations.runtimeClasspath.get()
        .onEach { println("add from dependencies: ${it.name}") }
        .map { if (it.isDirectory) it else zipTree(it) })
}
